### PR TITLE
Fix Building the OpenCOLLADAValidator when CMAKE_DEBUG_POSTFIX is set.

### PR DESCRIPTION
**Pull request by gaiaclary**
When CMAKE_DEBUG_POSTFIX is set then building OpenCOLLADAValidator did only work for release builds. For Debug builds the linker still searched for the libraries without the defined postfix and failed.

I also have renamed the vars LIBXML2_LIBRARIES and PCRE_LIBRARIES to singular:
LIBXML2_LIBRARY and PCRE_LIBRARY for better readability.

If at any time in the future these vars will contain more than one lib then it is time to change that back to plural.

### CODE REVIEW

**Comment by RemiArnaud** [comment]
what is CMAKE_DEBUG_POSTFIX for, and why do we need to maintain this ?

Debug and Release builds have been added to Jenkins for MAC and WINDOWS, and both work fine with current MASTER branch (without this PR).

I have no idea how to build debug for Linux ?

**Comment by gaiaclary** [comment]
This option allows to modify the library name. This is used in the Blender environment whith

CMAKE_DEBUG_POSTFIX=_d

The generated library files are then:

Release: OpenCOLLADABaseUtils.lib
Debug: OpenCOLLADABaseUtils_d.lib

Blender uses this naming scheme all over the place. Right now we can actually build the Collada libraries with the debug option (windows 7). The collada builder only creates an error when it builds the debug version of OpenCOLLADAValidator.

**Comment by RemiArnaud** [comment]
Can't you manually rename the files once they are produced? Or write a script that rename the files as you install them in your build environment?

is this addional conplexity really have to be in the opencollada build?

**Comment by gaiaclary** [comment]
I see your doubts. Actually we only need to build the libraries and not the executable programs for Blender. And the part of building the libraries actually works perfectly and it already uses the CMAKE_DEBUG_POSTFIX  as wanted. So we currently just build the OpenCOLLADAValidator and ignore the error message about missing libraries.

However if we can get a build target that only builds the libraries (using the already implemented CMAKE_DEBUG_POSTFIX parameter)  this would be even more elegant. I remember when i looked into this last time i was not able to find that build target nor create it (due to my lack of knowledge).

**Comment by RemiArnaud** [comment]
ok to test

**Comment by RemiArnaud** [comment]
test this please

**Comment by RemiArnaud** [comment]
I'm sorry, this fails to build. I'm closing it, but please submit new PR if you still need this.

Please note that we have progressed quite a lot, as we are now have tagged releases, so it makes it easier to build products using openCOLLADA as dependency. We provide binaries (currently on a dropbox share on opencollada.fl4re.com, and hopefully soon on github directly. We compile systematically openCOLLADA for ubuntu, mac, win; max and maya exporters for various versions of max,maya on PC and mac. Please contact me directly if you need more support.

remi (at) acm (dot) org

**Pull request closed without merging**
