### PR TITLE
Max layers to clips

### PR DESCRIPTION
**Pull request by mchudleigh**
An optional feature for ColladaMax that allows Max animation layers to be exported as named collada animations with referencing animation clips. It is effectively a way to export multiple complimentary animations from a single Max asset.

### CODE REVIEW

**Comment by RemiArnaud** [comment]
Ok to test

**Comment by RemiArnaud** [comment]
Test this please

**Comment by RemiArnaud** [comment]
test this please

**Comment by mchudleigh** [comment]
Alright, it looks like the Max build failed. When I try to view the build results with any of the supplied links I'm met with this error:
"mchudleigh is missing the Overall/Read permission"
This is even after giving Jenkins my github permissions.
Thoughts?

**Comment by RemiArnaud** [comment]
@mchudleigh yes, the jenkins build server is definitly not a public area.
I granted you access to the COLLADA-MAX-PC-PULL-REQUEST project.
you should be able to get the the console of build #121 http://50.250.211.65:7070/view/COLLADA/job/COLLADA-MAX-PC-PULL-REQUEST/121/console

scrolling down, you'll see this:
```
MAX 2011 X64 RELEASE            -- FAILED
MAX 2012 X64 RELEASE            -- FAILED
MAX 2013 X64 RELEASE            -- FAILED
MAX 2014 X64 RELEASE            -- FAILED
MAX 2015 X64 RELEASE            -- SUCCESS
MAX 2016 X64 RELEASE            -- SUCCESS
MAX 2011 X86 RELEASE            -- FAILED
MAX 2012 X86 RELEASE            -- FAILED
MAX 2013 X86 RELEASE            -- FAILED
MAX 2011 X64 RELEASE_STATIC     -- FAILED
MAX 2012 X64 RELEASE_STATIC     -- FAILED
MAX 2013 X64 RELEASE_STATIC     -- FAILED
MAX 2014 X64 RELEASE_STATIC     -- FAILED
MAX 2015 X64 RELEASE_STATIC     -- SUCCESS
MAX 2016 X64 RELEASE_STATIC     -- SUCCESS
MAX 2011 X86 RELEASE_STATIC     -- FAILED
MAX 2012 X86 RELEASE_STATIC     -- FAILED
MAX 2013 X64 RELEASE_STATIC     -- FAILED
MAX 2011 X64 DEBUG               -- FAILED
MAX 2012 X64 DEBUG              -- FAILED
MAX 2013 X64 DEBUG              -- FAILED
MAX 2014 X64 DEBUG              -- FAILED
MAX 2015 X64 DEBUG              -- SUCCESS
MAX 2016 X64 DEBUG              -- SUCCESS
MAX 2011 X86 DEBUG              -- FAILED
MAX 2012 X86 DEBUG              -- FAILED
MAX 2013 X86 DEBUG              -- FAILED
MAX 2011 X64 DEBUG_STATIC       -- FAILED
MAX 2012 X64 DEBUG_STATIC       -- FAILED
MAX 2013 X64 DEBUG_STATIC       -- FAILED
MAX 2015 X64 DEBUG_STATIC       -- FAILED
MAX 2015 X64 DEBUG_STATIC       -- SUCCESS
MAX 2016 X64 DEBUG_STATIC       -- SUCCESS
MAX 2011 X86 DEBUG_STATIC       -- FAILED
MAX 2012 X86 DEBUG_STATIC       -- FAILED
MAX 2013 X86 DEBUG_STATIC       -- FAILED
Found 28 error(s)
```

So basically it requires Max 2015 or Max 2016. Which is not a problem IHMO, new features work with newer versions of Max. However you'll have to make sure the other builds are not broken, so would need something that conditionally include the code based on MAX_RELEASE >= MAX_RELEASE_R17  

 The only outlier in those errors is  MAX 2015 X64 DEBUG_STATIC -- Failed

 turns out that's a bug in the build script, it should say MAX 2014... I just fixed it.

Regards
-- Remi

**Comment by mchudleigh** [comment]
Okay, that all makes sense. Unfortunately I still can not access the logs.
It is the same error as before.

**Comment by RemiArnaud** [comment]
I’m puzzled.

once logged into github as mchudleigh  you should have access to http://50.250.211.65:7070/view/COLLADA/job/COLLADA-MAX-PC-PULL-REQUEST

if this does not work, please give me an email address where I can send you the full log

Regards
— Remi

**Comment by mchudleigh** [comment]
Yeah, me too. I am definitely logged in, it says quite explicitly that
mchudleigh does not have permission.

In any case, you can send the logs to this email address:
matt.chudleigh@gmail.com

**Comment by RemiArnaud** [comment]
oh, I missed a place where to add the user.
it should work now?

**Comment by mchudleigh** [comment]
Yeah, it works now.

It looks like the C++11 features I was using are causing some problems. Is
C++11 not supported in the codebase?

**Comment by RemiArnaud** [comment]
Specific versions of sdk require specific versions of compilers (visual studio)


-- Rémi

**Comment by mchudleigh** [comment]
That's unfortunate, it does make sense though. I'll add the preprocessor
guards around the new code and resubmit.

**Comment by mchudleigh** [comment]
Compile time guards have been added. Please attempt another build.

**Comment by RemiArnaud** [comment]
test this please

**Comment by mchudleigh** [comment]
Well that was an unexpected bug.
On older Max SDK versions, MAX_RELEASE_R17 does not seem to be defined, so the guard always passed.
The new version is:
#if defined(MAX_RELEASE_R17) && (MAX_RELEASE >= MAX_RELEASE_R17)
if you'd like to try this one more time, please.

**Comment by RemiArnaud** [comment]
test this please

**Comment by RemiArnaud** [comment]
@mchudleigh thanks a lot for your contribution. 

Please download binary from http://opencollada.fl4re.com/  Follow the PULL_REQUEST#348

If you are happy with the result, please give me a green light for final merge.

**Comment by mchudleigh** [comment]
I'm perfectly fine with a merge if you are.

I will need to follow it up with another patch to extend it, but it has
quite a bit of value to us already.

Thanks!

**Pull request merged**
