### PR TITLE
Remove animation if all keys are the same

### PR DESCRIPTION
**Pull request by mycheckgithub**

### CODE REVIEW

**Comment by RemiArnaud** [comment]
ok to build

**Comment by RemiArnaud** [comment]
add to whitelist

**Comment by RemiArnaud** [comment]
ok to test

**Comment by RemiArnaud** [comment]
test this please

**Comment by RemiArnaud** [comment]
@mycheckgithub  this branch has conflicts

**Comment by mycheckgithub** [comment]
#371

**Pull request closed without merging**
