### PR TITLE
Feature/anim improvement

### PR DESCRIPTION
**Pull request by mycheckgithub**

### CODE REVIEW

**Comment by mycheckgithub** [comment]
https://github.com/fl4re/OpenCOLLADA/issues/23

**Comment by mycheckgithub** [comment]
https://github.com/fl4re/OpenCOLLADA/issues/10

**Comment by shane-calnan-sb** [comment]
Hi Franck,

If you have any questions regarding Mantis feel free to hit me up directly
and I'll help out. This particular issue I already moved over to Mantis (
https://starbreeze.mantishub.com/view.php?id=21191).

Thanks,

*Shane Calnan*
*Technical Producer*
Starbreeze Studios

**Comment by mycheckgithub** [comment]
retest this please

**Comment by RemiArnaud** [comment]
tested backed and non backed bezier skinned animation. works fine. Same animation as far as I can tell using OSX preview.

**Comment by RemiArnaud** [comment]
export time reported back to normal

**Pull request merged**
