### PR TITLE
Add MAYA2012 CgFX API code.

### PR DESCRIPTION
**Pull request by tak3110**

### CODE REVIEW

**Comment by RemiArnaud** [comment]
ok to build

**Comment by RemiArnaud** [comment]
retest this please

**Comment by jerome-jacob** [comment]
I tested this PR with a random cgfx downloaded from the net and get a malformed dae:

```xml
        <newparam sid="sampColor">
          <>
            <source>texColor</source>
            <minfilter>LINEAR</minfilter>
            <magfilter>LINEAR</magfilter>
            <mipmap_maxlevel>0</mipmap_maxlevel>
          </>
        </newparam>
```

(cgfx used: parallax one on this page http://kitfox.com/projects/shaders/index.html)

**Comment by tak3110** [comment]
@jerome-jacob Thanks. Please tell me MAYA version. This code supports MAYA2012.

**Comment by RemiArnaud** [comment]
Exporter has to support 2011 to 2016 included.  

You can download the binaries from this build on opencollada.fl4re.com, and you can get trial versions of maya from autodesk. 

However, it is possible to limit features to specific versions of Maya (or Max), but usually it is for newer versions, not older versions. For example, adding a feature that works for maya 2012 and higher versions. 

Best Regards

-- Rémi

**Comment by RemiArnaud** [comment]
forgot to mention, jerome tests were done with 2015 most likely

**Comment by jerome-jacob** [comment]
Indeed I tested with 2015, but I think the missing tag is due to an already present bug.

**Comment by jerome-jacob** [comment]
HwShaderExporter::getResourceType() only support "ResourceType" string for annotations. The cg file I tested uses "TextureType" string. Using "ResourceType" in the cg file fixes the issue.

**Comment by jerome-jacob** [comment]
Hi,

I did some additional tests with this pull request and found some issues:

- in COLLADAMayaMaterialExporter.cpp, String type is not supported in <setparam> element, remove the following case label:
case cgfxAttrDef::kAttrTypeString:

- COLLADAMayaHwShaderExporter.cpp, HwShaderExporter::exportSampler():
don't export <setparam> element if sampler has no texture associated (sampler.mImageId empty) or <init_from> will be empty which is not valid.

- several <setparam> with same ref and <newparam> with same sid are exported if samplers use the same texture

- "throw" statement when cgfx is not found: not sure if it's possible but maybe we could just skip parameters export instead?

Can you fix those issues?

**Comment by jerome-jacob** [comment]
All previously mentioned issues are not caused by this PR. I created separate issue tickets. This PR can be merged.

**Comment by RemiArnaud** [comment]
retest this please

**Pull request merged**
