### PR TITLE
Fix/step

### PR DESCRIPTION
**Pull request by mycheckgithub**

### CODE REVIEW

**Comment by krunal-patel-fl4re** [comment]
test this please

**Comment by RemiArnaud** [comment]
@krunal-patel-fl4re - jenkins is done with building master, let's start this PR build again

**Comment by RemiArnaud** [comment]
retest this please

**Comment by RemiArnaud** [comment]
@krunal-patel-fl4re - consistent build fail (http://50.250.211.65:7070//job/openCOLLADA-ubuntu-pull-request/92/)

```
ERROR: Publisher com.cloudbees.jenkins.GitHubCommitNotifier aborted due to exception
java.io.IOException: Cannot determine sha1 of the commit. The status cannot be reported
	at org.jenkinsci.plugins.github.util.BuildDataHelper.getCommitSHA1(BuildDataHelper.java:31)
	at com.cloudbees.jenkins.GitHubCommitNotifier.updateCommitStatus(GitHubCommitNotifier.java:102)
	at com.cloudbees.jenkins.GitHubCommitNotifier.perform(GitHubCommitNotifier.java:84)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:770)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:734)
	at hudson.model.Build$BuildExecution.post2(Build.java:183)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:683)
	at hudson.model.Run.execute(Run.java:1784)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)
Extended Email Publisher is currently disabled in project settings
Setting status of a787816f184fe5777a8edd2eaf5811deb6a26239 to FAILURE with url http://192.168.1.26/job/openCOLLADA-ubuntu-pull-request/92/ and message: Merged build finished.

Refer to this link for build results (access rights to CI server needed): 
http://50.250.211.65:7070//job/openCOLLADA-ubuntu-pull-request/92/
Test FAILed.
Finished: FAILURE```

**Comment by RemiArnaud** [comment]
@krunal-patel-fl4re - failed again

**Comment by RemiArnaud** [comment]
retest this please

**Comment by krunal-patel-fl4re** [comment]
retest this please

**Comment by krunal-patel-fl4re** [comment]
retest this please

**Comment by krunal-patel-fl4re** [comment]
retest this please

**Comment by Birdy3D** [comment]
ready to merge

**Comment by RemiArnaud** [comment]
thank you

**Pull request merged**
