### PR TITLE
Compilation fixes for linux (SCons build system)

### PR DESCRIPTION
**Pull request by gaiaclary**
- Unable to find ConvertUTF.h from CommonCharacterBuffer.cpp

- Missing _wfopen in CommonLogFileBufferFlusher.cpp, also
  missing include for fwrite, fclose, fopen, errno.

### CODE REVIEW

**Comment by RemiArnaud** [comment]
ok to test

**Comment by RemiArnaud** [comment]
test this please

**Comment by krunal-patel-fl4re** [comment]
test this please

**Comment by krunal-patel-fl4re** [comment]
test this please

**Comment by krunal-patel-fl4re** [comment]
test this please

**Comment by RemiArnaud** [comment]
fail mac build

git/workspace/openCOLLADA-mac-pull-request/common/libBuffer/include/CommonFWriteBufferFlusher.h:23:11: fatal error: 'tr1/unordered_map' file not found
#       include <tr1/unordered_map>

**Comment by RemiArnaud** [comment]
builds have been failing with this PR, and no remedy was provided. So I'll close this PR, but still welcome the changes in a new PR when ready.

**Pull request closed without merging**
