### PR TITLE
Misc/max 2018

### PR DESCRIPTION
**Pull request by ufoxp**
Fixes needed for 3DS MAX 2018.

### CODE REVIEW

**Comment by ufoxp** [comment]
This is definitely not enough. Google Warehouse and mesh extra export needs to be corrected.

**Comment by ufoxp** [comment]
Geometry extra export and Google Warehouse plugin load no longer crashes OpenCollada for 3DS MAX on 2018 version.
I've noticed that many geometry extra parameters are no longer exported. No idea if this is 20118 regression or was it broken before. Could somebody check on 2017 if cone radiuses are exported in extra?
Google Warehouse menu item insert no longer crashes 3DS MAX but after opening it there is still a crash. Was that the case on 2017?

**Comment by RemiArnaud** [comment]
@ufoxp - this is a branch from the KhronosGroup:misc/max-2018   
so if I were to merge this it would go first to the KhronosGroup:misc/max-2018 branch, and then would have to be merged to master branch.

it has conflicts, because we both modified the same files differently in our respective branch

Could you instead create a branch from KhronosGroup:master, cherry pick from KhronosGroup:misc/max-2018, then cherry pick your fixes from UfoProjects:misc/max-2018 to that new branch.

then create a new PR, which will now be based of master, from that new branch (delete his PR).
We'll get this new PR to build in jenkins. I'll delete KhronosGroup:misc/max-2018 and associated PR, and we'll merge your PR soon after.

I hope this make sense.
Thanks!

**Comment by ufoxp** [comment]
Erm, but this branch IS based on Khronos master. I deliberately removed temp file commit from your version of branch. This PR branched from master at a748c0e07e6b8bed78247a6b7b8bb780a6fe5a4d...

**Comment by RemiArnaud** [comment]
Yes. The branch was fine. But the PR was against the wrong branch
I edited the PR so it's now targeting master.

**Comment by RemiArnaud** [comment]
@ufoxp - I would like to merge this PR. 
Artifacts available in the message above. 

You can open a new branch and new PR to keep the work on this exporter. 

PS. let me know if you need to borrow a 2017 license.

**Comment by ufoxp** [comment]
I'm rather low on disk space so I would rather see someone else check stuff on 2017.

**Comment by RemiArnaud** [comment]
@ufoxp -  thanks for this contribtion and the testing. 
The plugin is functional now, but still has remaining issues that should be addressed in new PR(s) 
With this contribution max 2018 is added to the list of supported versions.

**Pull request merged**
