### PR TITLE
Misc/dae validator

### PR DESCRIPTION
**Pull request by jerome-jacob**
First version with:
- xsd validation
- unique id check

### CODE REVIEW

**Comment by RemiArnaud** [comment]
@mbarnes-sb - would you mind testing out the artifacts ? please?

**Comment by jerome-jacob** [comment]
FYI, usage is:
DAEValidator path_to_DAE --check-all|--check-unique-ids|--check-schema

**Comment by RemiArnaud** [comment]
@jerome-jacob can you please add minimum information in /README.md about what is ColladaValidator vs DaeValidator. why we have both? what's each program goal, future ... ?

**Comment by RemiArnaud** [comment]
testing required against dae set before merging

**Comment by jerome-jacob** [comment]
While testing against a dae set I found some minor issues that I fixed:
- validator can now be launched from any directory
- added a batch mode feature:
  - if passed parameter is a directory then the validator scans it and validates each dae found
  - "--recursive" option allows to recurse subdirectories
  - this avoids to use a batch file to process many daes and greatly improves performances
- added "--quiet" option to disable console output

**Pull request merged**
