### PR TITLE
Maya/physics extension impl

### PR DESCRIPTION
**Pull request by jerome-jacob**
PhysX extensions export.

### CODE REVIEW

**Comment by jerome-jacob** [comment]
retest this please

**Comment by RemiArnaud** [comment]
@mbarnes-sb - can you help with publishing extension specifications ? I suppose the right way would be to have the extension published through the Khronos collada wiki and then reference it from there?

**Comment by mbarnes-sb** [comment]
1. Create an account at https://www.khronos.org/collada/wiki/Main_page
2. Follow directions at https://www.khronos.org/collada/wiki/Portal:Extensions_directory
3. See specifically - https://www.khronos.org/collada/wiki/How_to_create_a_COLLADA_Extension#Implementing_and_advertising_extensions

**Comment by RemiArnaud** [comment]
@jerome, can you follow direction provided by Mark ?

Regards
-- Remi

**Comment by RemiArnaud** [comment]
@mbarnes-sb - how extension xsd get published ? should we establish a fl4re.com page for that ?

**Comment by mbarnes-sb** [comment]
@RemiArnaud ... Basically the validated schema needs to be permanently hosted so it's reachable on the internet. Instance documents reference it via ```xsi:schemaLocation``` or other legacy means. Generally the XML Namespace (xmlns) and schemaLocation match to support legacy means too.

See:
- https://www.w3.org/TR/xml-names11/
- https://www.w3.org/TR/xmlschema-1/#schema-loc
- http://stackoverflow.com/questions/34202967/xmlns-xmlnsxsi-and-xsischemalocation

**Comment by RemiArnaud** [comment]
ok, so can we have a web site created to host our extensions ?

**Comment by Birdy3D** [comment]
tested with various kind of testscenes, littles bugs has been correct, its a green light, i repeat , green light

**Comment by RemiArnaud** [comment]
thanks @Birdy3D - will merge as soon as I get the build working again after adding Maya 2017
@jerome-jacob - please work with @mbarnes-sb on the xsd
@mycheckgithub @jerome-jacob - let's post all extensions (as read-only public google docs) on the extension registry https://www.khronos.org/collada/wiki/Portal:Extensions_directory

**Pull request merged**
