### PR TITLE
fixed wrong image path

### PR DESCRIPTION
**Pull request by jerome-jacob**
Wrong image path when using relative paths

### CODE REVIEW

**Comment by krunal-patel-fl4re** [comment]
test this please

**Comment by krunal-patel-fl4re** [comment]
test this please

**Comment by RemiArnaud** [comment]
testing fixes to build system. A slave PC had to be rebooted.
Need to run build again after colladaMaya has built

**Comment by jerome-jacob** [comment]
retest this please

**Comment by RemiArnaud** [comment]
@krunal-patel-fl4re could you take a look at http://50.250.211.65:7070/job/COLLADA-MAX-PC-PULL-REQUEST/117/console ?
Something to fix on this slave, or should we rebuild this PR again AS-IS ?

**Comment by jerome-jacob** [comment]
retest this please

**Pull request merged**
