### PR TITLE
Fix defect of export CgFx blend function.

### PR DESCRIPTION
**Pull request by tak3110**
After this fix. We can get blend function.

Ex. After
```
        <technique sid="SubtractiveBlend">
          <pass sid="p0">
            <depth_test_enable value="true"/>
            <depth_func value="LEQUAL"/>
            <blend_enable value="true"/>
            <blend_func><src value="SRC_ALPHA" /><dest value="ONE" /></blend_func>
            <blend_equation value="FUNC_REVERSE_SUBTRACT"/>
```

Ex. Before
```
        <technique sid="SubtractiveBlend">
          <pass sid="p0">
            <depth_test_enable value="true"/>
            <depth_func value="LEQUAL"/>
            <blend_enable value="true"/>
            <blend_func value="UNKNOWN INPUT ERROR" value="UNKNOWN INPUT ERROR"/>
            <blend_equation value="UNKNOWN INPUT ERROR"/>
```

### CODE REVIEW

**Comment by RemiArnaud** [comment]
retest this please

**Comment by RemiArnaud** [comment]
@tak3110 this breaks the mac build with following error:

/Users/manu/git/workspace/Maya-2015-mac-pull-request/COLLADAMaya/src/COLLADAMayaHwShaderExporter.cpp:335:17: error: no matching function for call to 'transform'
                std::transform( cgStateName.begin(), cgStateName.end(), cgStateName.begin(), std::tolower );
                ^~~~~~~~~~~~~~
In file included from /Users/manu/git/workspace/Maya-2015-mac-pull-request/COLLADAMaya/src/COLLADAMayaHwShaderExporter.cpp:16:
In file included from /Users/manu/git/workspace/Maya-2015-mac-pull-request/COLLADAMaya/include/COLLADAMayaStableHeaders.h:35:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/vector:265:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__bit_reference:15:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:1922:1: note: candidate template ignored: couldn't infer template argument '_UnaryOperation'
transform(_InputIterator __first, _InputIterator __last, _OutputIterator __result, _UnaryOperation __op)
^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:1932:1: note: candidate function template not viable: requires 5 arguments, but 4 were provided

**Comment by RemiArnaud** [comment]
Warning - this PR will be closed if the issue reported above is not fixed.

**Comment by tak3110** [comment]
Thanks. I will fix as soon as.  But, I have no times.

**Comment by tak3110** [comment]
@RemiArnaud Hi, I don't have xcode. 
How could I test it ?
I think this comple error will fixed. Please see below.
http://stackoverflow.com/questions/7131858/stdtransform-and-toupper-no-matching-function

**Comment by RemiArnaud** [comment]
The Bot will build it, you just have to update the code. 
Thanks!

-- Rémi

**Comment by RemiArnaud** [comment]
@tak3110 - could you add the fix to your branch so we can build?

I agree the solution is probably to make sure compiler finds the proper signature

template< class InputIt, class OutputIt, class UnaryOperation >
OutputIt transform( InputIt first1, InputIt last1, OutputIt d_first,
                    UnaryOperation unary_op );

**Comment by RemiArnaud** [comment]
@tak3110 I closed this PR because its not building. Please open a new PR when you have the time

**Pull request closed without merging**
