### PR TITLE
Fix issue #430

### PR DESCRIPTION
**Pull request by mycheckgithub**
https://github.com/KhronosGroup/OpenCOLLADA/issues/430

### CODE REVIEW

**Comment by krunal-patel-fl4re** [comment]
retest this please

**Comment by RemiArnaud** [comment]
rebuild with SP5 and 2017 builds now checked in

**Comment by RemiArnaud** [comment]
test this please

**Comment by RemiArnaud** [comment]
@mycheckgithub  can you please merge master in your branch ?

**Pull request merged**
