### PR TITLE
Update COLLADAMaxMorphControllerCreator.cpp

### PR DESCRIPTION
**Pull request by corentinjaffre**
morpher crash colladamax on 3dsmax 2014.

### CODE REVIEW

**Comment by RemiArnaud** [comment]
ok to test

**Comment by RemiArnaud** [comment]
test this please

**Comment by corentinjaffre** [comment]
I tested the plug-in with the commented morpher line, and it's loading!
I already exported a few meshes, and for now, it's working well. 
Thanks everyone :)

**Comment by RemiArnaud** [comment]
Ok, so this is a good work around. How do we fix this for everyone now is the question ?

Should we build 2 exporters and let users try out?
Should we remove morphing support forever?
Is there a way to build without this dependency (build in the feature) ?

**Comment by RemiArnaud** [comment]
real fix now in https://github.com/KhronosGroup/OpenCOLLADA/pull/444

**Pull request closed without merging**
