### PR TITLE
Added animation clip parsing and writer callbacks

### LINKED ISSUE #565: Support for importing library animation clips
Hi;
I am trying to add support for library animation clips to the Blender Collada Importer. The problem is that according to the specification animations shall only be applied to the scene animation playback when they are **not** referenced by any library animation clip:

From the Collada 1.4 Spec document:

> _animations_ that are referred to and used in _animation_clips_ should not be applied to the
> scene at playback time; instead, apply only unreferenced _animations_ to the scene (used for 
> playback).
> Note: Plug-in implementors must support this strategy even if they do not fully support
> _animation_clip_. For example, DCC tools can store the contents of _library_animations_ and
> _library_animation_clips_ in banks or palettes. Any unreferenced _animation_ is left to be
> processed according to the application run-time; these are the ones to load and play.

However during import i just get the defined instance_animations one after the other and i can not figure out which of them i shall import as library animation and which of them i shall import directly to the scene playback.

Any Help? Any example function where i can look at?
btw: Exporting libary animation clips was no problem with OpenCollada.

### PR DESCRIPTION
**Pull request by lasalvavida**
Resolves #565 and enables multiple animations support in COLLADA2GLTF: https://github.com/KhronosGroup/COLLADA2GLTF/issues/130.

### CODE REVIEW

**Comment by RemiArnaud** [comment]
In file included from /var/lib/jenkins/workspace/openCOLLADA-ubuntu-pull-request/COLLADAValidator/src/../include/Writer.h:5:0,
                 from /var/lib/jenkins/workspace/openCOLLADA-ubuntu-pull-request/COLLADAValidator/src/main.cpp:1:
/var/lib/jenkins/workspace/openCOLLADA-ubuntu-pull-request/COLLADAFramework/include/COLLADAFWIWriter.h:114:42: error: ‘AnimationClip’ does not name a type
   virtual bool writeAnimationClip( const AnimationClip* animationClip ) = 0;
                                          ^
/var/lib/jenkins/workspace/openCOLLADA-ubuntu-pull-request/COLLADAFramework/include/COLLADAFWIWriter.h:114:57: error: ISO C++ forbids declaration of ‘animationClip’ with no type [-fpermissive]
   virtual bool writeAnimationClip( const AnimationClip* animationClip ) = 0;
                                                         ^
/var/lib/jenkins/workspace/openCOLLADA-ubuntu-pull-request/COLLADAValidator/src/main.cpp: In function ‘void parse(char*, ValidationErrorHandler&)’:
/var/lib/jenkins/workspace/openCOLLADA-ubuntu-pull-request/COLLADAValidator/src/main.cpp:33:11: error: cannot declare variable ‘writer’ to be of abstract type ‘Writer’
  ::Writer writer;
           ^
In file included from /var/lib/jenkins/workspace/openCOLLADA-ubuntu-pull-request/COLLADAValidator/src/main.cpp:1:0:
/var/lib/jenkins/workspace/openCOLLADA-ubuntu-pull-request/COLLADAValidator/src/../include/Writer.h:13:7: note:   because the following virtual functions are pure within ‘Writer’:
 class Writer : public COLLADAFW::IWriter
       ^
In file included from /var/lib/jenkins/workspace/openCOLLADA-ubuntu-pull-request/COLLADAValidator/src/../include/Writer.h:5:0,
                 from /var/lib/jenkins/workspace/openCOLLADA-ubuntu-pull-request/COLLADAValidator/src/main.cpp:1:
/var/lib/jenkins/workspace/openCOLLADA-ubuntu-pull-request/COLLADAFramework/include/COLLADAFWIWriter.h:114:16: note: 	virtual bool COLLADAFW::IWriter::writeAnimationClip(const int*)
   virtual bool writeAnimationClip( const AnimationClip* animationClip ) = 0;

**Comment by lasalvavida** [comment]
Thanks @RemiArnaud. Will update the other IWriter subclasses in this project to have the new animation clip stub.

**Comment by RemiArnaud** [comment]
..\src\COLLADAMaxColladaImporter.cpp(127): error C2259: 'COLLADAMax::DocumentImporter' : cannot instantiate abstract class [e:\git\workspace\COLLADA-MAX-PC-PULL-REQUEST\COLLADAMax\scripts\COLLADAMax.vcxproj]
                 due to following members:
                 'bool COLLADAFW::IWriter::writeAnimationClip(const COLLADAFW::AnimationClip *)' : is abstract
                 ..\..\COLLADAFramework\include\COLLADAFWIWriter.h(115) : see declaration of 'COLLADAFW::IWriter::writeAnimationClip'

**Comment by RemiArnaud** [comment]
COLLADA-MAX:

COLLADASaxFrameworkLoader.lib(COLLADASaxFWLRootParser14.obj) : error LNK2001: unresolved external symbol "public: __cdecl COLLADASaxFWL::LibraryAnimationClipsLoader::LibraryAnimationClipsLoader(class COLLADASaxFWL::IFilePartLoader *)" (??0LibraryAnimationClipsLoader@COLLADASaxFWL@@QEAA@PEAVIFilePartLoader@1@@Z) [e:\git\workspace\COLLADA-MAX-PC-PULL-REQUEST\COLLADAMax\scripts\COLLADAMax.vcxproj]
         COLLADASaxFrameworkLoader.lib(COLLADASaxFWLRootParser14.obj) : error LNK2001: unresolved external symbol "public: virtual bool __cdecl COLLADASaxFWL::LibraryAnimationClipsLoader14::end__library_animation_clips(void)" (?end__library_animation_clips@LibraryAnimationClipsLoader14@COLLADASaxFWL@@UEAA_NXZ) [e:\git\workspace\COLLADA-MAX-PC-PULL-REQUEST\COLLADAMax\scripts\COLLADAMax.vcxproj]
         COLLADASaxFrameworkLoader.lib(COLLADASaxFWLRootParser14.obj) : error LNK2001: unresolved external symbol "public: virtual bool __cdecl COLLADASaxFWL::LibraryAnimationClipsLoader14::begin__animation_clip(struct COLLADASaxFWL14::animation_clip__AttributeData const &)" (?begin__animation_clip@LibraryAnimationClipsLoader14@COLLADASaxFWL@@UEAA_NAEBUanimation_clip__AttributeData@COLLADASaxFWL14@@@Z) [e:\git\workspace\COLLADA-MAX-PC-PULL-REQUEST\COLLADAMax\scripts\COLLADAMax.vcxproj]
         COLLADASaxFrameworkLoader.lib(COLLADASaxFWLRootParser14.obj) : error LNK2001: unresolved external symbol "public: virtual bool __cdecl COLLADASaxFWL::LibraryAnimationClipsLoader14::end__animation_clip(void)" (?end__animation_clip@LibraryAnimationClipsLoader14@COLLADASaxFWL@@UEAA_NXZ) [e:\git\workspace\COLLADA-MAX-PC-PULL-REQUEST\COLLADAMax\scripts\COLLADAMax.vcxproj]
         COLLADASaxFrameworkLoader.lib(COLLADASaxFWLRootParser14.obj) : error LNK2001: unresolved external symbol "public: virtual bool __cdecl COLLADASaxFWL::LibraryAnimationClipsLoader14::begin__instance_animation(struct COLLADASaxFWL14::instance_animation__AttributeData const &)" (?begin__instance_animation@LibraryAnimationClipsLoader14@COLLADASaxFWL@@UEAA_NAEBUinstance_animation__AttributeData@COLLADASaxFWL14@@@Z) [e:\git\workspace\COLLADA-MAX-PC-PULL-REQUEST\COLLADAMax\scripts\COLLADAMax.vcxproj]
         COLLADASaxFrameworkLoader.lib(COLLADASaxFWLRootParser14.obj) : error LNK2001: unresolved external symbol "public: virtual bool __cdecl COLLADASaxFWL::LibraryAnimationClipsLoader14::end__instance_animation(void)" (?end__instance_animation@LibraryAnimationClipsLoader14@COLLADASaxFWL@@UEAA_NXZ) [e:\git\workspace\COLLADA-MAX-PC-PULL-REQUEST\COLLADAMax\scripts\COLLADAMax.vcxproj]
         COLLADASaxFrameworkLoader.lib(COLLADASaxFWLRootParser15.obj) : error LNK2001: unresolved external symbol "public: virtual bool __cdecl COLLADASaxFWL::LibraryAnimationClipsLoader15::end__library_animation_clips(void)" (?end__library_animation_clips@LibraryAnimationClipsLoader15@COLLADASaxFWL@@UEAA_NXZ) [e:\git\workspace\COLLADA-MAX-PC-PULL-REQUEST\COLLADAMax\scripts\COLLADAMax.vcxproj]
         COLLADASaxFrameworkLoader.lib(COLLADASaxFWLRootParser15.obj) : error LNK2001: unresolved external symbol "public: virtual bool __cdecl COLLADASaxFWL::LibraryAnimationClipsLoader15::begin__animation_clip(struct COLLADASaxFWL15::animation_clip__AttributeData const &)" (?begin__animation_clip@LibraryAnimationClipsLoader15@COLLADASaxFWL@@UEAA_NAEBUanimation_clip__AttributeData@COLLADASaxFWL15@@@Z) [e:\git\workspace\COLLADA-MAX-PC-PULL-REQUEST\COLLADAMax\scripts\COLLADAMax.vcxproj]
         COLLADASaxFrameworkLoader.lib(COLLADASaxFWLRootParser15.obj) : error LNK2001: unresolved external symbol "public: virtual bool __cdecl COLLADASaxFWL::LibraryAnimationClipsLoader15::end__animation_clip(void)" (?end__animation_clip@LibraryAnimationClipsLoader15@COLLADASaxFWL@@UEAA_NXZ) [e:\git\workspace\COLLADA-MAX-PC-PULL-REQUEST\COLLADAMax\scripts\COLLADAMax.vcxproj]
         COLLADASaxFrameworkLoader.lib(COLLADASaxFWLRootParser15.obj) : error LNK2001: unresolved external symbol "public: virtual bool __cdecl COLLADASaxFWL::LibraryAnimationClipsLoader15::begin__instance_animation(struct COLLADASaxFWL15::instance_animation__AttributeData const &)" (?begin__instance_animation@LibraryAnimationClipsLoader15@COLLADASaxFWL@@UEAA_NAEBUinstance_animation__AttributeData@COLLADASaxFWL15@@@Z) [e:\git\workspace\COLLADA-MAX-PC-PULL-REQUEST\COLLADAMax\scripts\COLLADAMax.vcxproj]
         COLLADASaxFrameworkLoader.lib(COLLADASaxFWLRootParser15.obj) : error LNK2001: unresolved external symbol "public: virtual bool __cdecl COLLADASaxFWL::LibraryAnimationClipsLoader15::end__instance_animation(void)" (?end__instance_animation@LibraryAnimationClipsLoader15@COLLADASaxFWL@@UEAA_NXZ) [e:\git\workspace\COLLADA-MAX-PC-PULL-REQUEST\COLLADAMax\scripts\COLLADAMax.vcxproj]
         ..\bin\win\x64\Release_Max2011\COLLADAMaxNew.dle : fatal error LNK1120: 11 unresolved externals [e:\git\workspace\COLLADA-MAX-PC-PULL-REQUEST\COLLADAMax\scripts\COLLADAMax.vcxproj]

COLLADA-MAYA:
  2>COLLADASaxFrameworkLoader.lib(COLLADASaxFWLRootParser14.obj) : error LNK2001: unresolved external symbol "public: __cdecl COLLADASaxFWL::LibraryAnimationClipsLoader::LibraryAnimationClipsLoader(class COLLADASaxFWL::IFilePartLoader *)" (??0LibraryAnimationClipsLoader@COLLADASaxFWL@@QEAA@PEAVIFilePartLoader@1@@Z) [e:\git\workspace\COLLADA-MAYA-PC-PULL-REQUEST\COLLADAMaya\scripts\COLLADAMaya.vcxproj]
     2>COLLADASaxFrameworkLoader.lib(COLLADASaxFWLRootParser14.obj) : error LNK2001: unresolved external symbol "public: virtual bool __cdecl COLLADASaxFWL::LibraryAnimationClipsLoader14::end__library_animation_clips(void)" (?end__library_animation_clips@LibraryAnimationClipsLoader14@COLLADASaxFWL@@UEAA_NXZ) [e:\git\workspace\COLLADA-MAYA-PC-PULL-REQUEST\COLLADAMaya\scripts\COLLADAMaya.vcxproj]
     2>COLLADASaxFrameworkLoader.lib(COLLADASaxFWLRootParser14.obj) : error LNK2001: unresolved external symbol "public: virtual bool __cdecl COLLADASaxFWL::LibraryAnimationClipsLoader14::begin__animation_clip(struct COLLADASaxFWL14::animation_clip__AttributeData const &)" (?begin__animation_clip@LibraryAnimationClipsLoader14@COLLADASaxFWL@@UEAA_NAEBUanimation_clip__AttributeData@COLLADASaxFWL14@@@Z) [e:\git\workspace\COLLADA-MAYA-PC-PULL-REQUEST\COLLADAMaya\scripts\COLLADAMaya.vcxproj]
     2>COLLADASaxFrameworkLoader.lib(COLLADASaxFWLRootParser14.obj) : error LNK2001: unresolved external symbol "public: virtual bool __cdecl COLLADASaxFWL::LibraryAnimationClipsLoader14::end__animation_clip(void)" (?end__animation_clip@LibraryAnimationClipsLoader14@COLLADASaxFWL@@UEAA_NXZ) [e:\git\workspace\COLLADA-MAYA-PC-PULL-REQUEST\COLLADAMaya\scripts\COLLADAMaya.vcxproj]
     2>COLLADASaxFrameworkLoader.lib(COLLADASaxFWLRootParser14.obj) : error LNK2001: unresolved external symbol "public: virtual bool __cdecl COLLADASaxFWL::LibraryAnimationClipsLoader14::begin__instance_animation(struct COLLADASaxFWL14::instance_animation__AttributeData const &)" (?begin__instance_animation@LibraryAnimationClipsLoader14@COLLADASaxFWL@@UEAA_NAEBUinstance_animation__AttributeData@COLLADASaxFWL14@@@Z) [e:\git\workspace\COLLADA-MAYA-PC-PULL-REQUEST\COLLADAMaya\scripts\COLLADAMaya.vcxproj]
     2>COLLADASaxFrameworkLoader.lib(COLLADASaxFWLRootParser14.obj) : error LNK2001: unresolved external symbol "public: virtual bool __cdecl COLLADASaxFWL::LibraryAnimationClipsLoader14::end__instance_animation(void)" (?end__instance_animation@LibraryAnimationClipsLoader14@COLLADASaxFWL@@UEAA_NXZ) [e:\git\workspace\COLLADA-MAYA-PC-PULL-REQUEST\COLLADAMaya\scripts\COLLADAMaya.vcxproj]
     2>COLLADASaxFrameworkLoader.lib(COLLADASaxFWLRootParser15.obj) : error LNK2001: unresolved external symbol "public: virtual bool __cdecl COLLADASaxFWL::LibraryAnimationClipsLoader15::end__library_animation_clips(void)" (?end__library_animation_clips@LibraryAnimationClipsLoader15@COLLADASaxFWL@@UEAA_NXZ) [e:\git\workspace\COLLADA-MAYA-PC-PULL-REQUEST\COLLADAMaya\scripts\COLLADAMaya.vcxproj]
     2>COLLADASaxFrameworkLoader.lib(COLLADASaxFWLRootParser15.obj) : error LNK2001: unresolved external symbol "public: virtual bool __cdecl COLLADASaxFWL::LibraryAnimationClipsLoader15::begin__animation_clip(struct COLLADASaxFWL15::animation_clip__AttributeData const &)" (?begin__animation_clip@LibraryAnimationClipsLoader15@COLLADASaxFWL@@UEAA_NAEBUanimation_clip__AttributeData@COLLADASaxFWL15@@@Z) [e:\git\workspace\COLLADA-MAYA-PC-PULL-REQUEST\COLLADAMaya\scripts\COLLADAMaya.vcxproj]
     2>COLLADASaxFrameworkLoader.lib(COLLADASaxFWLRootParser15.obj) : error LNK2001: unresolved external symbol "public: virtual bool __cdecl COLLADASaxFWL::LibraryAnimationClipsLoader15::end__animation_clip(void)" (?end__animation_clip@LibraryAnimationClipsLoader15@COLLADASaxFWL@@UEAA_NXZ) [e:\git\workspace\COLLADA-MAYA-PC-PULL-REQUEST\COLLADAMaya\scripts\COLLADAMaya.vcxproj]
     2>COLLADASaxFrameworkLoader.lib(COLLADASaxFWLRootParser15.obj) : error LNK2001: unresolved external symbol "public: virtual bool __cdecl COLLADASaxFWL::LibraryAnimationClipsLoader15::begin__instance_animation(struct COLLADASaxFWL15::instance_animation__AttributeData const &)" (?begin__instance_animation@LibraryAnimationClipsLoader15@COLLADASaxFWL@@UEAA_NAEBUinstance_animation__AttributeData@COLLADASaxFWL15@@@Z) [e:\git\workspace\COLLADA-MAYA-PC-PULL-REQUEST\COLLADAMaya\scripts\COLLADAMaya.vcxproj]
     2>COLLADASaxFrameworkLoader.lib(COLLADASaxFWLRootParser15.obj) : error LNK2001: unresolved external symbol "public: virtual bool __cdecl COLLADASaxFWL::LibraryAnimationClipsLoader15::end__instance_animation(void)" (?end__instance_animation@LibraryAnimationClipsLoader15@COLLADASaxFWL@@UEAA_NXZ) [e:\git\workspace\COLLADA-MAYA-PC-PULL-REQUEST\COLLADAMaya\scripts\COLLADAMaya.vcxproj]
     2>..\bin\win\x64\ReleasePlugin2018\COLLADAMaya.mll : fatal error LNK1120: 11 unresolved externals [e:\git\workspace\COLLADA-MAYA-PC-PULL-REQUEST\COLLADAMaya\scripts\COLLADAMaya.vcxproj]

**Pull request closed without merging**
