### PR TITLE
added 2014 SP5 fix

### PR DESCRIPTION
**Pull request by RemiArnaud**

### CODE REVIEW

**Comment by RemiArnaud** [comment]
FATAL: hudson.remoting.Channel$OrderlyShutdown
hudson.remoting.RequestAbortedException: hudson.remoting.Channel$OrderlyShutdown

??

**Comment by RemiArnaud** [comment]
test this please

**Comment by RemiArnaud** [comment]
@mycheckgithub @jerome-jacob 
error LNK2001: unresolved external symbol "__declspec(dllimport) public: void __cdecl morphChannel::buildFromNode(class INode *,int,int,int,int)" (__imp_?buildFromNode@morphChannel@@QEAAXPEAVINode@@HHHH@Z) [e:\git\workspace\COLLADA-MAX-PC-PULL-REQUEST\COLLADAMax\scripts\COLLADAMax.vcxproj]

so, afterall I do need a SDK 2014 SP5, but I have no idea where to find this.

Please someone help, where can I find this?

**Comment by RemiArnaud** [comment]
test this please

**Comment by RemiArnaud** [comment]
@mycheckgithub @jerome-jacob   Ah! Looks like I managed to create a 2104 SDK SP5
@krunal-patel-fl4re  - I made an install on a PC, applied SP5, copied the SP5 SDK folder on build machine.

**Comment by RemiArnaud** [comment]
spoke too fast, 3dsmax is not finish uilding ...

**Comment by RemiArnaud** [comment]
test this please

**Comment by RemiArnaud** [comment]
same problem, the SDK I copied does not work

         COLLADAMaxMorphControllerCreator.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: void __cdecl morphChannel::buildFromNode(class INode *,int,int,int,int)" (__imp_?buildFromNode@morphChannel@@QEAAXPEAVINode@@HHHH@Z) [e:\git\workspace\COLLADA-MAX-PC-PULL-REQUEST\COLLADAMax\scripts\COLLADAMax.vcxproj]

@mycheckgithub - were you able to compile this? can you send me your SDK folder ?

**Comment by mycheckgithub** [comment]
Please replace with this PR

https://github.com/KhronosGroup/OpenCOLLADA/pull/445

**Comment by RemiArnaud** [comment]
replaced by https://github.com/KhronosGroup/OpenCOLLADA/pull/445

**Pull request closed without merging**
