### PR TITLE
adding maya2018 support

### PR DESCRIPTION
**Pull request by RemiArnaud**

### CODE REVIEW

**Comment by RemiArnaud** [comment]
error MSB8020: The build tools for v140 (Platform Toolset = 'v140') cannot be found. To build using the v140 build tools, please install v140 build tools.

@krunal-patel-fl4re, I am having trouble with this job COLLADA-MAYA-PC-PULL-REQUEST..

**Comment by ThomasVeil** [comment]
Is there a way (for a noob) to download a version with this fix? I really need Maya2018 support.

**Comment by RemiArnaud** [comment]
I can't get the ConsoleRelease build to work. the Debug build seems fine.
I looked a this long enough now to think the problem is in the Maya SDK itself.
So I removed this target from the CI build for now, to unblock 2018 users

@ThomasVeil and all, the 2018 artifacts are available at https://s3-us-west-2.amazonaws.com/opencollada-pr-artifacts/opencollada_OCPR-549_OCTESTSPR-_COLLADA-MAYA-PC-PULL-REQUEST_build_432_Maya2018.zip  could you test and let me know if this works for you

I need to figure out how to change the message to publish the link in the fl4rebot message

**Comment by ThomasVeil** [comment]
Ah, thanks so much @RemiArnaud. It worked - no errors when starting the plugin (that's where it used to give up before) - and I got a DAE file out of it. Might still have to see if these files come out perfectly fine - but looks promising so far. This will save me a ton of time.

**Comment by krunal-patel-fl4re** [comment]
@RemiArnaud for review

**Comment by RemiArnaud** [comment]
Thanks Krunal.. let see what master builds does now ....

**Pull request merged**
