### PR TITLE
Added animation clip parsing and writer callbacks

### LINKED ISSUE #565: Support for importing library animation clips
Hi;
I am trying to add support for library animation clips to the Blender Collada Importer. The problem is that according to the specification animations shall only be applied to the scene animation playback when they are **not** referenced by any library animation clip:

From the Collada 1.4 Spec document:

> _animations_ that are referred to and used in _animation_clips_ should not be applied to the
> scene at playback time; instead, apply only unreferenced _animations_ to the scene (used for 
> playback).
> Note: Plug-in implementors must support this strategy even if they do not fully support
> _animation_clip_. For example, DCC tools can store the contents of _library_animations_ and
> _library_animation_clips_ in banks or palettes. Any unreferenced _animation_ is left to be
> processed according to the application run-time; these are the ones to load and play.

However during import i just get the defined instance_animations one after the other and i can not figure out which of them i shall import as library animation and which of them i shall import directly to the scene playback.

Any Help? Any example function where i can look at?
btw: Exporting libary animation clips was no problem with OpenCollada.

### PR DESCRIPTION
**Pull request by lasalvavida**
Resolves #565 and enables multiple animations support in COLLADA2GLTF: KhronosGroup/COLLADA2GLTF#130.

Re-opened from #592.

Contains updated Visual Studio definitions to hopefully resolve the Maya/Max build issue present in the other PR.

### CODE REVIEW

**Comment by lasalvavida** [comment]
@RemiArnaud, if you're okay with it, I'd like to get this pushed through before normalizing formatting since it's holding things up on the COLLADA2GLTF side of things.

**Comment by RemiArnaud** [comment]
Maya Mac Release 2015:

COLLADASaxFrameworkLoader/src/COLLADASaxFWLRootParser15.cpp:25:10: fatal error: 'COLLADASaxFWLLibraryAnimationClipsLoader15.h' file not found

COLLADASaxFrameworkLoader/src/COLLADASaxFWLRootParser14.cpp:25:10: fatal error: 'COLLADASaxFWLLibraryAnimationClipsLoader14.h' file not found

The MAX issue is a server configuration issue I'll fix asap

**Comment by lasalvavida** [comment]
I have updated the relevant XCode project; hopefully that's the last thing.

After formatting fixes, if you would like, I can take a look at unifying the CMake build a bit. Unless there's a really good reason, It just seems little unintuitive to use CMake across most of the project, but also have checked in Visual Studio and XCode projects.

**Comment by RemiArnaud** [comment]
COLLADASaxFrameworkLoader/src/COLLADASaxFWLRootParser15.cpp:25:10: fatal error: 'COLLADASaxFWLLibraryAnimationClipsLoader15.h' file not found
#include "COLLADASaxFWLLibraryAnimationClipsLoader15.h"

**Comment by lasalvavida** [comment]
After some difficulty setting up a Mac OS VM, I've updated the XCode project for COLLADAMaya. 🤞

**Comment by lasalvavida** [comment]
@RemiArnaud, could you take a look at this when you get a chance? I'd like to try to get this merged at some point during this week.

**Review by RemiArnaud — APPROVED** [review]
Thanks for the contribution

**Comment by lasalvavida** [comment]
Awesome, thanks @RemiArnaud!

**Pull request merged**
