### PR TITLE
Fix for building on Debian scons

### PR DESCRIPTION
**Pull request by gaiaclary**
SCONS builds seem to be broken on linux. The following patch adds some includes and defines a function that is used by opencollada but seems to be only available on windows platforms.

I apologize for the number of commits for this fix. I had some problems with synchronizing the repositories with my previous patch. The actual changes in this patch are very small.

### CODE REVIEW

**Comment by gaiaclary** [comment]
after talking with some others about this issue we came to the conclusion that actually the files can be deleted:

common/libBuffer/include/CommonLogFileBufferFlusher.cpp
common/libBuffer/include/CommonLogFileBufferFlusher.h

The class defined there seems to be nowhere used.

**Comment by gaiaclary** [comment]
Hi
I really would like to use the newest opencollada library for blender 2.79. Right now this pull request fixes the only roadblock for building blender.

Since apparently the broken function is not used in opencollada and since that function is disabled for cmake builds, please can you consider to also disable this function from scons builds ? or delete it entirely if that suits better ?

thanks
cheers,
Gaia

**Comment by gaiaclary** [comment]
It seems like nobody feels responsible for this issue?
I really want to know how to proceed here :(

thanks
cheers,
Gaia

**Comment by RemiArnaud** [comment]
Sorry about the delay. I started a build / test and if it goes through this will be merged.

thanks for your help and patience !

**Comment by RemiArnaud** [comment]
Or feel free to delete those files in this PR/branch. We'll get another build/test and merge.
We'll go by your choice.

**Comment by gaiaclary** [comment]
Hi, Remi;
Since the files are not used in the cmake build i believe its best to just delete them. 
This keeps future developers from wondering :)

I have updated the pull request accordingly.
However i have not tested with SCons. But it looks like the SCons scripts take care of the source files automatically?

It would be nice to get this merged soon so that i can recommend updating the openColladalilbraries for Blender 2.79

Thanks a lot !
cheers,
Gaia

**Comment by RemiArnaud** [comment]
The build with the fix works, but removing the files fails the windows build.

**Comment by RemiArnaud** [comment]
The max and maya builds fail. Maybe it is because the project include those files are they are not needed.  OpenCOLLADA builds ok on all platforms. 

Maybe it is because those files are actually needed by the windows build of the plugins. This would have to be investigated. 

For the sake of time, so I can make the merge asap for you, I'd recommend reverting to fixing the files and keeping them in the repo, removing them from openCollada builds still.

**Comment by gaiaclary** [comment]
I have reverted the previous commit, so the files are available again. 

* For CMake builds all seems well, the files are apparently not used for the library builds.
* For SCons builds i am not sure how to keep the files and remove them from the library builds.

You have an Advise ?

**Comment by mbarnes-sb** [comment]
```
       (ClCompile target) -> 
         c1xx : fatal error C1083: Cannot open source file: '..\src\CommonLogFileBufferFlusher.cpp': No such file or directory [e:\git\workspace\COLLADA-MAYA-PC-PULL-REQUEST\common\libBuffer\scripts\libBuffer.vcxproj]
```
```
       (ClCompile target) -> 
         c1xx : fatal error C1083: Cannot open source file: '..\src\CommonLogFileBufferFlusher.cpp': No such file or directory [e:\git\workspace\COLLADA-MAX-PC-PULL-REQUEST\common\libBuffer\scripts\libBuffer.vcxproj]
```

**Comment by RemiArnaud** [comment]
@mbarnes-sb. Yes. The question is about keeping the files - so plugin build succeed, but removing from scons makefiles (i have never used scons)

**Comment by RemiArnaud** [comment]
@mbarnes-sb - last build failed on network issue pushing to S3

**Comment by mbarnes-sb** [comment]
I think the file is referenced from `common\libBuffer\scripts\libBuffer.vcxproj`

**Comment by gaiaclary** [comment]
@mbarnes-sb: right, i have seen that. But i did not know how this file was constructed so i kept far away from modifying it by hand :) I hoped that someone more familiar with the building of OpenCollada could solve the mystery there. 

All i can say is that the files that i proposed to delete are not used anywhere in the opencollada sources.

**Pull request merged**
