### PR TITLE
Places the contributor inside the asset tags.

### PR DESCRIPTION
**Pull request by glaforte**

### CODE REVIEW

**Comment by RemiArnaud** [comment]
Ok to test

**Comment by RemiArnaud** [comment]
test this please

**Comment by RemiArnaud** [comment]
@glaforte so the bot is happy with the build, next step is to do some testing that the plugin generally works and that particular issue is fixed. 
For Max, the robot say the artifacts can be downloaded on  http://www.opencollada.org/ following the folder path PULL_REQUEST#406/COLLADAMax/2016-02-19_18-58-15_#203

Just leave a message here when you can confirm this is good to merge. 

Thanks!

**Comment by glaforte** [comment]
Hey Remi,

Are you hosting the pull request builds on DropBox?
CM Labs' network is blocking DropBox :(


Guillaume

**Comment by RemiArnaud** [comment]
yes, its on dropbox.

where do you want me to put it ?

**Comment by RemiArnaud** [comment]
@glaforte 
We think this https://github.com/KhronosGroup/OpenCOLLADA/pull/408 is the cause of all trouble.
and that this should fix the bug without asking everyone to make changes to their exporter...

can you send me an email, so I can send you the binaries for this other PR ?
I don't have your email address
remi (at) acm (dot) org

thanks

**Comment by RemiArnaud** [comment]
Closing this PR because original cause of this issue was solved in #408

**Pull request closed without merging**
