### PR TITLE
Split Anim/Mesh DAE

### PR DESCRIPTION
**Pull request by mycheckgithub**

### CODE REVIEW

**Comment by RemiArnaud** [comment]
retest this please

**Comment by RemiArnaud** [comment]
(see if scripts are copied in dropbox now)

**Comment by RemiArnaud** [comment]
@mbarnes-sb @mycheckgithub - could you work together to see if there is a way (via asset tag?) to have some information that help linking the exported files together. I'm not sure there is a really good solution here, but maybe this can be improved a little?

@mycheckgithub - can you make sure a single clip (or maybe a selection of clips?) can be exported

**Comment by mycheckgithub** [comment]
Fix to provide selection of clips to be exported in Bezier Mode (Baked mode was ok)
In Trax Editor you have multiselection of clips and with right click have "Enable Clip"

**Comment by mycheckgithub** [comment]
As Mark told us during the meeting, in <asset> there is <source_data>.
It will be the same between Mesh/Anim DAE.
Do we need a better solution ?

**Comment by joshochoa** [comment]
I have tested this and all things appear to be working.

Thank you!

**Comment by RemiArnaud** [comment]
Thanks Josh!

 @mycheckgithub I'll merge as soon as you add some doc. Probably the readme in COLLADAMaya folder is a good place to get some documentation started

**Comment by RemiArnaud** [comment]
@mycheckgithub - branch in conflict. 
 Also, please add mini doc on Maya export options

**Pull request merged**
