### PR TITLE
Add non skinned element to controller array

### PR DESCRIPTION
**Pull request by mycheckgithub**

### CODE REVIEW

**Comment by RemiArnaud** [comment]
I am very worried changing default exporter behavior. At least this should be a option, off by default.
This requires documentation.

**Comment by RemiArnaud** [comment]
Notes anout thos PR. 
For some reason, nodes in the skeleton can be includedin animation, but removed from controller because they have no influence. This PR fixed this by adding all skeleton nodes to the array of inverse world bind matrices.
There is no other way to get this data, since the exporter set default transforms to the initial step of the animation, not the bind pose. 
This should not inpact any existing software to have this additional information.

**Comment by mycheckgithub** [comment]
https://github.com/KhronosGroup/OpenCOLLADA/issues/372

**Comment by atoll** [comment]
You were right to be concerned about this change Remi. I just recently updated to the most recent OpenCOLLADA source in out tool chain and this change causes problems for our rig pipeline because we are always getting the entire skeleton in the skin controllers instead of just the influence joints.

**Pull request merged**
