### PR TITLE
max 2018 jenkins build

### PR DESCRIPTION
**Pull request by RemiArnaud**

### CODE REVIEW

**Comment by mbarnes-sb** [comment]
Log says the .sln is not setup for that configuration ...
```
Build started 8/9/2017 8:29:47 PM.
     1>Project "e:\git\workspace\COLLADA-MAX-PC-PULL-REQUEST\COLLADAMax\COLLADAMax.sln" on node 1 (build target(s)).
     1>e:\git\workspace\COLLADA-MAX-PC-PULL-REQUEST\COLLADAMax\COLLADAMax.sln.metaproj : error MSB4126: The specified solution configuration "Release_Max2018|x64" is invalid. Please specify a valid solution configuration using the Configuration and Platform properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use the default solution configuration. [e:\git\workspace\COLLADA-MAX-PC-PULL-REQUEST\COLLADAMax\COLLADAMax.sln]
     1>Done Building Project "e:\git\workspace\COLLADA-MAX-PC-PULL-REQUEST\COLLADAMax\COLLADAMax.sln" (build target(s)) -- FAILED.

Build FAILED.

```

**Comment by RemiArnaud** [comment]
Yeah. I m not sure the same config can be used to compil for SDK 2017 and SDK 2018 so I have not yet installed the necessary requirements for 2018 on jenkins agents and not added 2018 to the build. 

I have a question about this here https://stackoverflow.com/questions/45602561/can-i-use-visual-studio-2015-update-3-with-3dsmax-2017-sdk

**Comment by RemiArnaud** [comment]
I installed win sdk and vs 2017 update 3 to autobuildPC. Added 2018 sln.

**Comment by RemiArnaud** [comment]
2>..\include\COLLADAMaxStableHeaders.h(52): fatal error C1189: #error: ( "Unsupported Max version" )

**Comment by RemiArnaud** [comment]
build failed in the testing phase, problem with Maya 2015 license.
fixed license issue, let's build again

**Comment by RemiArnaud** [comment]
Compilation error for Max2018:
   4>..\src\COLLADAMaxGeometryExtra.cpp(552): error C2248: 'SimpleObject2::pblock2': cannot access protected member declared in class 'SimpleObject2' [e:\git\workspace\COLLADA-MAX-PC-PULL-REQUEST\COLLADAMax\scripts\COLLADAMax.vcxproj]
         E:\Program Files\Autodesk\3ds Max 2018 SDK\maxsdk\include\simpobj.h(254): note: see declaration of 'SimpleObject2::pblock2'

**Comment by RemiArnaud** [comment]
Hum... now 2018 builds in debug, but fails in release build.
All other versions (2011-2017) succeed build

MAX 2018 X64 RELEASE            -- FAILED
error LNK2001: unresolved external symbol __imp__invalid_parameter
MAX 2018 X64 RELEASE_STATIC     -- FAILED

MAX 2018 X64 DEBUG              -- SUCCESS
MAX 2018 X64 DEBUG_STATIC       -- SUCCESS

**Comment by RemiArnaud** [comment]
hum, ok now we need to change the jenkins job to add the max 2018 artifacts...

**Comment by krunal-patel-fl4re** [comment]
this is done.

**Pull request closed without merging**
